### ISSUE TITLE
Linux Suggestion: Serial group isn't consistent across distros

### ISSUE THREAD

**Issue by tyisafk** [rmull/tinkup#4]
Reading the readme, not every distro uses the dialout group (Usually used by Ubuntu) for serial devices.  For example, Arch Linux uses a group called uucp for this.

Of course this only applies to people who don't want to use sudo, but it would save some headaches for them who runs a distro that doesn't have the dialout group.

You can check the group you need to add yourself to with `stat /dev/ttyUSB0` while the Tink is plugged in and checking `Gid`

Example output:
```
  File: /dev/ttyUSB0
  Size: 0               Blocks: 0          IO Block: 4096   character special file
Device: 0,5     Inode: 1033        Links: 1     Device type: 188,0
Access: (0660/crw-rw----)  Uid: (    0/    root)   Gid: (  986/    uucp)
Access: 2022-04-18 21:31:14.408052160 -0400
Modify: 2022-04-18 21:31:14.408052160 -0400
Change: 2022-04-18 21:31:14.408052160 -0400
 Birth: -
```

**Comment by rmull** [comment]
Thanks for the suggestion - I generalized the instructions approximately according to your recommendation.
